IBM_API_KEY = "JBpbQIgKy05VABESGDRziDJn_mvuDnbw4CckGJcWFv-r"
IBM_PROJECT_ID = "cadd32bb-dfe7-45ba-be47-c679947a2f5d"
IBM_URL = "https://us-south.ml.cloud.ibm.com"
GEMINI_API_KEY = "AIzaSyA6tlYw6tXCO75IPN3Tj1GzFFPgkWnUh6A"
